### ISSUE TITLE
[Kubuntu] RuntimeException if plugin is not configured

### ISSUE THREAD

**Issue by ofry** [sburlyaev/IDEA-Native-Terminal-Plugin#23]
```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019

JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Kubuntu 18.10 64-bit
```

Native Terminal v0.3.3

```
java.lang.RuntimeException: Failed to execute the command!
	at com.sburlyaev.cmd.plugin.actions.OpenTerminalBaseAction.actionPerformed(OpenTerminalBaseAction.java:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:184)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:148)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:410)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: Cannot run program "gnome-terminal": error=2, Нет такого файла или каталога
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.sburlyaev.cmd.plugin.model.Command.execute(Command.java:24)
	at com.sburlyaev.cmd.plugin.actions.OpenTerminalBaseAction.actionPerformed(OpenTerminalBaseAction.java:39)
	... 37 more
Caused by: java.io.IOException: error=2, Нет такого файла или каталога
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 39 more
```

**Comment by sburlyaev** [comment]
Hi @ofry,
By default it uses gnome-terminal. Looks like kubuntu doesn't have this terminal pre-installed..

**Comment by ofry** [comment]
Maybe try to launch Konsole (KDE terminal application) too?

**Comment by sburlyaev** [comment]
Makes sense.
Could you please share some lines from your idea.log file - [Locating IDE log files](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)?
Actually, I am interested in 'OpenTerminalBaseAction - Environment' line.
Thanks!

**Comment by ofry** [comment]
```
ofryak@ofryak-virtual-machine:~/.IntelliJIdea2018.3/system/log$ for file in ./*log*; do grep --line-number --with-filename '.*OpenTerminal.*' $file ; done
```

no output

**Comment by sburlyaev** [comment]
I am not sure about actual grep command, but the log message should look like this:
`09:47:36,438 [ 346122]   INFO - actions.OpenTerminalBaseAction - Environment{os=WINDOWS, osVersion='10.0', gui='windows'}`
with specific OS variables, of course.

**Comment by ofry** [comment]
```
./idea.log:4442:2019-03-21 16:01:24,353 [1987876]   INFO - actions.OpenTerminalBaseAction - Environment{os=LINUX, osVersion='4.18.0-17-generic', gui='null'} 
```

**Comment by sburlyaev** [comment]
Thanks! will think how to handle this.

**Comment by sburlyaev** [comment]
Hi @ofry,
Is this still relevant?

**Comment by ofry** [comment]
Thank you for adding Konsole support.
